name: Build project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run Linting
        run: npm run lint
  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, tests]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: |
          echo "Starting Deployment to Azure..."
          echo "Deplying..."
      
